### ISSUE TITLE
SIGABRT after window resize

### ISSUE THREAD

**Issue by KillWolfVlad** [KoczurekK/sf-svg#1]
Hi! I need draw colored (with alpha-channel) svg images in my program. And I want resize window and scale svg to fill window. So, I rasterize svg with needed scale factor to Image, then create Texture from Image, and apply this Texture to RectangleShape. But when I resize window (not always) I get `SIGABRT` on [this](https://github.com/KoczurekK/sf-svg/blob/master/SFC/nanosvg%2B%2B/Nanosvgrastr.cpp#L1273) line, or [this](https://github.com/KoczurekK/sf-svg/blob/master/SFC/nanosvg%2B%2B/Nanosvgrastr.cpp#L1299) line or [this](https://github.com/KoczurekK/sf-svg/blob/master/SFC/nanosvg%2B%2B/Nanosvgrastr.cpp#L162).

I created test project to reproduce this issue (your should pass path to svg in arguments, and press down to set window size 800x450, but this size may not work)

https://github.com/KillWolfVlad/sf-svg-SIGABRT

My environment is Arch Linux GNOME 3 on Xorg (intel modesetting) with latest update from official repo. But I have this issue on Ubuntu 16.04 (in VirtualBox) and Windows (sf-svg compiles only in STATIC mode, and need invoke rasterize before drawing, because resize event is not handled after launch).

I think it is bug in nanosvg, but sf-svg fork is older than upstream.

**Comment by kamirr** [comment]
It should be working properly now, but I kept this issue open just in case. It was actually my mistake as for some sizes rounding caused using memory that wasn't actually allocated. Because you're probably going to switch to the newest sf-svg, it's worth pointing out that to link the library you should pass
`-lsfsvg`, not `-lsf-svg` as the in CMake file that you've provided.

**Comment by KillWolfVlad** [comment]
Perfect work on Arch Linux and Windows, thank you!
